### ISSUE TITLE
Consider integrating with fluxcd for source tracking

### ISSUE THREAD

**Issue by derrickburns** [pulumi/pulumi-kubernetes-operator#158] opened 2021-06-14 00:04 UTC
If I understand the Pulumi Kubernetes operator correctly, it executes Pulumi updates by pulling code from Git from within Kubernetes.  

For this application, you may want to consider integrating with FluxCD v2. It provides the tracking of Git repos for changes that appears to be missing from the Pulumi operator.

**Comment by lukehoban** [comment] 2021-06-14 04:36
This is largely what is being tracking in #50, so I'll close this out as a dupe of that.  I added the more explicit note there that the likely approach we'll want to take is to build on the support for Git polling that already exists in a reusable form in Flux or Argo.

**Comment by viveklak** [comment] 2021-07-23 18:42
Breaking out the suggestion to use flux etc. from #50 here instead.
Some possibilities here include integrating with https://fluxcd.io/docs/components/source/gitrepositories/. This could allow users to choose to install the [Flux Source Controller](https://fluxcd.io/docs/components/source/) to use that or the Bucket source as a source for content that triggers reconciliation in the operator.

**Comment by viveklak** [comment] 2022-07-29 16:14
An added benefit here is to leverage support for a variety of source control providers which have been known to cause problems with go-git - the library that the underlying automation api uses for git integration. See #302 and #286 for instance.

**Comment by lblackstone** [comment] 2022-10-24 22:01
Fixed in https://github.com/pulumi/pulumi-kubernetes-operator/pull/324

**Closed by lblackstone** 2022-10-24 22:01 UTC
Labels: kind/enhancement, resolution/fixed
